IP        = "10.42.0.223"
bitfile   = "spec_2in_2048ch_983mhz_real.fpg"
adc_bits  = 16
program   = true

[snapshots]
snap_names = ["adc_snapshot0", "adc_snapshot1"]
n_samples  = 256

[spectra]
bram_names = [["spec0_0", "spec0_1", "spec0_2", "spec0_3"],
              ["spec1_0", "spec1_1", "spec1_2", "spec1_3"],
              ["spec2_0", "spec2_1", "spec2_2", "spec2_3"]]
addr_width = 9
data_width = 64
bandwidth  = 983.04 # MHz
dBFS       = 96
reset_reg  = "cnt_rst"
acc_reg    = "acc_len"
acc_len    = 65536

[multiband]
invert_delay = 384
